apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
   build: consultaservicios
  name: consultaservicios
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: consultaservicios:latest
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: fuse7-java11-openshift:1.9
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
