package com.oracle.xmlns.pcbpel.adapter.db.sbappamsa_tes_12c.sca.db_scaconsultaserviciosref;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-15T11:04:49.517-03:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "db_SCAConsultaServiciosRef_ptt-bindingQSService",
                  wsdlLocation = "file:/home/jeremy/gitlab/Amsa0.1/SCA%20Servicios/13122021/PXE80004_ConsultaServicios/src/main/resources/wsdl/db_SCAConsultaServiciosRef-concrete.wsdl",
                  targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/db/SBAppAMSA_TES_12c/SCA/db_SCAConsultaServiciosRef")
public class DbSCAConsultaServiciosRefPttBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/SBAppAMSA_TES_12c/SCA/db_SCAConsultaServiciosRef", "db_SCAConsultaServiciosRef_ptt-bindingQSService");
    public final static QName DbSCAConsultaServiciosRefPttBindingQSPort = new QName("http://xmlns.oracle.com/pcbpel/adapter/db/SBAppAMSA_TES_12c/SCA/db_SCAConsultaServiciosRef", "db_SCAConsultaServiciosRef_ptt-bindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jeremy/gitlab/Amsa0.1/SCA%20Servicios/13122021/PXE80004_ConsultaServicios/src/main/resources/wsdl/db_SCAConsultaServiciosRef-concrete.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DbSCAConsultaServiciosRefPttBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/jeremy/gitlab/Amsa0.1/SCA%20Servicios/13122021/PXE80004_ConsultaServicios/src/main/resources/wsdl/db_SCAConsultaServiciosRef-concrete.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DbSCAConsultaServiciosRefPttBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DbSCAConsultaServiciosRefPttBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DbSCAConsultaServiciosRefPttBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DbSCAConsultaServiciosRefPttBindingQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DbSCAConsultaServiciosRefPttBindingQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DbSCAConsultaServiciosRefPttBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DbSCAConsultaServiciosRefPtt
     */
    @WebEndpoint(name = "db_SCAConsultaServiciosRef_ptt-bindingQSPort")
    public DbSCAConsultaServiciosRefPtt getDbSCAConsultaServiciosRefPttBindingQSPort() {
        return super.getPort(DbSCAConsultaServiciosRefPttBindingQSPort, DbSCAConsultaServiciosRefPtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DbSCAConsultaServiciosRefPtt
     */
    @WebEndpoint(name = "db_SCAConsultaServiciosRef_ptt-bindingQSPort")
    public DbSCAConsultaServiciosRefPtt getDbSCAConsultaServiciosRefPttBindingQSPort(WebServiceFeature... features) {
        return super.getPort(DbSCAConsultaServiciosRefPttBindingQSPort, DbSCAConsultaServiciosRefPtt.class, features);
    }

}
